// Package metaparser parses the textproto EBNF grammar via gluon v2 and
// compiles it into a protobuf FileDescriptorProto.
package metaparser

import (
	"fmt"
	"sort"
	"strings"

	"github.com/accretional/gluon/v2/compiler"
	"github.com/accretional/gluon/v2/metaparser"
	"github.com/accretional/proto-textproto/lang"
	"google.golang.org/protobuf/types/descriptorpb"
)

// EBNF returns the embedded textproto EBNF grammar source.
func EBNF() []byte {
	return lang.EBNF
}

// CompileResult holds the output of compiling the EBNF grammar.
type CompileResult struct {
	FileDescriptor *descriptorpb.FileDescriptorProto
	RuleCount      int
	ASTChildCount  int
}

// Compile parses the EBNF source and compiles it to a FileDescriptorProto.
func Compile(ebnfSrc []byte) (*CompileResult, error) {
	doc := metaparser.WrapString(string(ebnfSrc))
	gd, err := metaparser.ParseEBNF(doc)
	if err != nil {
		return nil, fmt.Errorf("ParseEBNF: %w", err)
	}

	ast, err := compiler.GrammarToAST(gd)
	if err != nil {
		return nil, fmt.Errorf("GrammarToAST: %w", err)
	}

	fdp, err := compiler.Compile(ast, compiler.Options{
		Package:   "textproto",
		GoPackage: "github.com/accretional/proto-textproto/proto/gen;textprotopb",
		FileName:  "textproto.proto",
	})
	if err != nil {
		return nil, fmt.Errorf("Compile: %w", err)
	}

	return &CompileResult{
		FileDescriptor: fdp,
		RuleCount:      len(gd.GetRules()),
		ASTChildCount:  len(ast.GetRoot().GetChildren()),
	}, nil
}

// SerializeProto converts a FileDescriptorProto into .proto file text.
func SerializeProto(fdp *descriptorpb.FileDescriptorProto) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Generated by metaparser from textproto.ebnf — DO NOT EDIT.\nsyntax = %q;\n\n", fdp.GetSyntax()))
	b.WriteString(fmt.Sprintf("package %s;\n\n", fdp.GetPackage()))

	if fdp.GetOptions() != nil && fdp.GetOptions().GetGoPackage() != "" {
		b.WriteString(fmt.Sprintf("option go_package = %q;\n\n", fdp.GetOptions().GetGoPackage()))
	}

	for _, dep := range fdp.GetDependency() {
		b.WriteString(fmt.Sprintf("import %q;\n", dep))
	}
	if len(fdp.GetDependency()) > 0 {
		b.WriteString("\n")
	}

	for _, msg := range fdp.GetMessageType() {
		writeMessage(&b, msg, 0)
		b.WriteString("\n")
	}

	return b.String()
}

func writeMessage(b *strings.Builder, msg *descriptorpb.DescriptorProto, indent int) {
	prefix := strings.Repeat("  ", indent)
	b.WriteString(fmt.Sprintf("%smessage %s {\n", prefix, msg.GetName()))

	for _, nested := range msg.GetNestedType() {
		writeMessage(b, nested, indent+1)
		b.WriteString("\n")
	}

	oneofNames := make([]string, len(msg.GetOneofDecl()))
	oneofFields := make(map[int32][]int)
	for i, od := range msg.GetOneofDecl() {
		oneofNames[i] = od.GetName()
	}
	for i, f := range msg.GetField() {
		if f.OneofIndex != nil {
			idx := f.GetOneofIndex()
			oneofFields[idx] = append(oneofFields[idx], i)
		}
	}

	oneofIndices := make([]int32, 0, len(oneofFields))
	for idx := range oneofFields {
		oneofIndices = append(oneofIndices, idx)
	}
	sort.Slice(oneofIndices, func(i, j int) bool { return oneofIndices[i] < oneofIndices[j] })

	writtenFields := make(map[int]bool)
	fieldPrefix := strings.Repeat("  ", indent+1)

	for _, oIdx := range oneofIndices {
		b.WriteString(fmt.Sprintf("%soneof %s {\n", fieldPrefix, oneofNames[oIdx]))
		for _, fIdx := range oneofFields[oIdx] {
			f := msg.GetField()[fIdx]
			writeField(b, f, indent+2)
			writtenFields[fIdx] = true
		}
		b.WriteString(fmt.Sprintf("%s}\n", fieldPrefix))
	}

	for i, f := range msg.GetField() {
		if writtenFields[i] {
			continue
		}
		writeField(b, f, indent+1)
	}

	b.WriteString(fmt.Sprintf("%s}\n", prefix))
}

func writeField(b *strings.Builder, f *descriptorpb.FieldDescriptorProto, indent int) {
	prefix := strings.Repeat("  ", indent)
	label := ""
	if f.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED {
		label = "repeated "
	}
	typeName := protoTypeName(f)
	b.WriteString(fmt.Sprintf("%s%s%s %s = %d;\n", prefix, label, typeName, f.GetName(), f.GetNumber()))
}

func protoTypeName(f *descriptorpb.FieldDescriptorProto) string {
	switch f.GetType() {
	case descriptorpb.FieldDescriptorProto_TYPE_STRING:
		return "string"
	case descriptorpb.FieldDescriptorProto_TYPE_MESSAGE:
		tn := f.GetTypeName()
		tn = strings.TrimPrefix(tn, ".")
		return tn
	default:
		return f.GetType().String()
	}
}
