package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/accretional/gluon/v2/compiler"
	"github.com/accretional/gluon/v2/metaparser"
	"google.golang.org/protobuf/types/descriptorpb"
)

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "usage: ebnf2proto <input.ebnf> <output.proto>\n")
		os.Exit(1)
	}
	ebnfPath := os.Args[1]
	outPath := os.Args[2]

	src, err := os.ReadFile(ebnfPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", ebnfPath, err)
		os.Exit(1)
	}

	// Step 1: Parse EBNF → GrammarDescriptor
	doc := metaparser.WrapString(string(src))
	gd, err := metaparser.ParseEBNF(doc)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ParseEBNF: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Parsed %d rules from EBNF\n", len(gd.GetRules()))
	for _, r := range gd.GetRules() {
		fmt.Printf("  rule: %s (%d expressions)\n", r.GetName(), len(r.GetExpressions()))
	}

	// Step 2: GrammarDescriptor → ASTDescriptor
	ast, err := compiler.GrammarToAST(gd)
	if err != nil {
		fmt.Fprintf(os.Stderr, "GrammarToAST: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("AST root has %d children\n", len(ast.GetRoot().GetChildren()))

	// Step 3: ASTDescriptor → FileDescriptorProto
	fdp, err := compiler.Compile(ast, compiler.Options{
		Package:   "textproto",
		GoPackage: "github.com/accretional/proto-textproto/proto/gen;textprotopb",
		FileName:  "textproto.proto",
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Compile: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated proto with %d messages, %d dependencies\n",
		len(fdp.GetMessageType()), len(fdp.GetDependency()))

	// Step 4: Serialize FileDescriptorProto → .proto text
	protoText := serializeProto(fdp)

	if err := os.WriteFile(outPath, []byte(protoText), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("Wrote %s\n", outPath)
}

func serializeProto(fdp *descriptorpb.FileDescriptorProto) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Generated by ebnf2proto from textproto.ebnf — DO NOT EDIT.\nsyntax = %q;\n\n", fdp.GetSyntax()))
	b.WriteString(fmt.Sprintf("package %s;\n\n", fdp.GetPackage()))

	if fdp.GetOptions() != nil && fdp.GetOptions().GetGoPackage() != "" {
		b.WriteString(fmt.Sprintf("option go_package = %q;\n\n", fdp.GetOptions().GetGoPackage()))
	}

	for _, dep := range fdp.GetDependency() {
		b.WriteString(fmt.Sprintf("import %q;\n", dep))
	}
	if len(fdp.GetDependency()) > 0 {
		b.WriteString("\n")
	}

	for _, msg := range fdp.GetMessageType() {
		writeMessage(&b, msg, 0)
		b.WriteString("\n")
	}

	return b.String()
}

func writeMessage(b *strings.Builder, msg *descriptorpb.DescriptorProto, indent int) {
	prefix := strings.Repeat("  ", indent)
	b.WriteString(fmt.Sprintf("%smessage %s {\n", prefix, msg.GetName()))

	// Write nested types first
	for _, nested := range msg.GetNestedType() {
		writeMessage(b, nested, indent+1)
		b.WriteString("\n")
	}

	// Collect oneof names for field annotation
	oneofNames := make([]string, len(msg.GetOneofDecl()))
	oneofFields := make(map[int32][]int) // oneof index → field indices
	for i, od := range msg.GetOneofDecl() {
		oneofNames[i] = od.GetName()
	}
	for i, f := range msg.GetField() {
		if f.OneofIndex != nil {
			idx := f.GetOneofIndex()
			oneofFields[idx] = append(oneofFields[idx], i)
		}
	}

	// Sort oneof indices for deterministic output
	oneofIndices := make([]int32, 0, len(oneofFields))
	for idx := range oneofFields {
		oneofIndices = append(oneofIndices, idx)
	}
	sort.Slice(oneofIndices, func(i, j int) bool { return oneofIndices[i] < oneofIndices[j] })

	// Write non-oneof fields and oneof blocks
	writtenFields := make(map[int]bool)
	fieldPrefix := strings.Repeat("  ", indent+1)

	// Write oneof blocks
	for _, oIdx := range oneofIndices {
		b.WriteString(fmt.Sprintf("%soneof %s {\n", fieldPrefix, oneofNames[oIdx]))
		for _, fIdx := range oneofFields[oIdx] {
			f := msg.GetField()[fIdx]
			writeField(b, f, indent+2)
			writtenFields[fIdx] = true
		}
		b.WriteString(fmt.Sprintf("%s}\n", fieldPrefix))
	}

	// Write remaining (non-oneof) fields
	for i, f := range msg.GetField() {
		if writtenFields[i] {
			continue
		}
		writeField(b, f, indent+1)
	}

	b.WriteString(fmt.Sprintf("%s}\n", prefix))
}

func writeField(b *strings.Builder, f *descriptorpb.FieldDescriptorProto, indent int) {
	prefix := strings.Repeat("  ", indent)
	label := ""
	if f.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED {
		label = "repeated "
	}

	typeName := protoTypeName(f)
	b.WriteString(fmt.Sprintf("%s%s%s %s = %d;\n", prefix, label, typeName, f.GetName(), f.GetNumber()))
}

func protoTypeName(f *descriptorpb.FieldDescriptorProto) string {
	switch f.GetType() {
	case descriptorpb.FieldDescriptorProto_TYPE_STRING:
		return "string"
	case descriptorpb.FieldDescriptorProto_TYPE_MESSAGE:
		// Strip leading dot and package prefix for local types
		tn := f.GetTypeName()
		tn = strings.TrimPrefix(tn, ".")
		return tn
	default:
		return f.GetType().String()
	}
}
